apiVersion: v1
kind: Service
metadata:
  name: novamarket-service
  labels:
    app: novamarket
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
      nodePort: 30080
  selector:
    app: novamarket
