@startuml
participant Сервис_корзины
participant Сервис_склада
participant Сервис_оплаты
participant Сервис_доставки
participant Сервис_заказов
actor Пользователь

== Оформление заказа ==
Сервис_корзины -> Сервис_заказов : Событие: Заказ оформлен
Сервис_заказов -> Пользователь : Изменение статуса заказа()
Сервис_корзины -> Сервис_заказов : Событие: Заказ отменен
Сервис_заказов -> Пользователь : Изменение статуса заказа()
Сервис_корзины -> Сервис_заказов : Событие: Заказ не прошел
Сервис_заказов -> Пользователь : Изменение статуса заказа()
== Резервирование товара ==
Сервис_склада -> Сервис_заказов : Событие: товар закончился
Сервис_заказов -> Пользователь : Изменение статуса заказа()
== Оплата заказа ==
Сервис_оплаты -> Сервис_заказов : Событие: Оплата прошла
Сервис_заказов -> Пользователь : Изменение статуса заказа()
Сервис_оплаты -> Сервис_заказов : Событие: Оплата отклонена
Сервис_заказов -> Пользователь : Изменение статуса заказа()
Сервис_оплаты -> Сервис_заказов : Событие: Вышло время на оплату
Сервис_заказов -> Пользователь : Изменение статуса заказа()
== Изменение доставки ==
Сервис_доставки -> Сервис_заказов : Событие: Получен трек-номер стороннего сервиса доставки
Сервис_заказов -> Пользователь : Изменение статуса заказа()
Сервис_доставки -> Сервис_заказов : Событие: Заказ передан в доставку
Сервис_заказов -> Пользователь : Изменение статуса заказа()
Сервис_доставки -> Сервис_заказов : Событие: Заказ доставлен
Сервис_заказов -> Пользователь : Изменение статуса заказа()
@enduml