@startuml

== товар есть в наличии ==

actor Пользователь
participant Сервис_склада
participant Сервис_корзины

Пользователь -> Сервис_склада : Выбор товара для добавления в корзину()
Сервис_склада -> Сервис_корзины : Событие: Товар выбран

Сервис_корзины -> Сервис_корзины: Добавление товара()
Сервис_корзины -> Пользователь: Обновление корзины()

== товара нет на складе ==

Пользователь -> Сервис_склада : Выбор товара для добавления в корзину()
Сервис_склада -> Пользователь : Отказ()

@enduml