@startuml
actor Пользователь
participant Сервис_корзины
participant Сервис_склада
participant Сервис_оплаты
participant Сервис_доставки
participant Сервис_уведомлений
participant Сервис_заказов
actor Продавец

== Успешное проведение заказа ==

Пользователь -> Сервис_корзины : Оформление заказа()
Сервис_корзины -> Сервис_склада : Событие: заказ оформлен
Сервис_склада -> Сервис_оплаты : Событие: товар забронирован
Сервис_оплаты -> Сервис_доставки : Событие: оплата подтверждена
Сервис_доставки -> Сервис_уведомлений : Событие: создана заявка на доставку 
Сервис_уведомлений -> Продавец : Отправка уведомления()

== Оплата не прошла ==

Сервис_оплаты -> Сервис_оплаты : Проведение оплаты()
group
Сервис_оплаты -> Сервис_склада : Событие: Оплата не прошла
Сервис_оплаты -> Сервис_корзины : Событие: Оплата не прошла
end
Сервис_склада -> Сервис_склада : Отмена резервирования()
Сервис_корзины -> Пользователь : Возврат товаров в корзину()

== Истекло время оплаты ==

Сервис_оплаты -> Сервис_оплаты : Срабатывание таймера()
group
Сервис_оплаты -> Сервис_склада : Событие: Истекло время оплаты
Сервис_оплаты -> Сервис_корзины : Событие: Истекло время оплаты
end
Сервис_склада -> Сервис_склада : Отмена резервирования()
Сервис_корзины -> Пользователь : Возврат товаров в корзину()

== Товара нет на складе ==

Сервис_склада -> Сервис_склада : Ошибка резервирования()
Сервис_склада -> Сервис_корзины : Событие: Товара нет на складе
Сервис_корзины -> Пользователь : Уведомление()

@enduml