@startuml NovaMarket_C2
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()

title Контекстная диаграмма: NovaMarket ED

System_Boundary(novamarket, "NovaMarket", "Kubernetes") {
    Component(api_gateway, "MarketController", "Apollo Federation", "Main API gateway")
    Component(notificationService, "Notification Service", "Java", "Отправка уведомлений")

    ' Microservices
    Container_Boundary(store, "Store Microservice", "Склад товаров") {
        Component(storeService, "Store Service", "Java", "Учет товаров, резервирование и отгрузка")
        ComponentDb(postgres_store, "Store DB", "PostgreSQL", "Данные о складских запасах")
    }

    Container_Boundary(catalog, "Catalog Microservice", "Каталог продукции") {
        Component(catalogService, "Catalog Service", "Java", "Полная информация о товарах и ценах")
        ComponentDb(postgres_catalog, "Catalog DB", "PostgreSQL", "Данные товаров, отзывы")
    }

    Container_Boundary(basket, "Basket Microservice", "Корзина покупателя") {
        Component(basketService, "Basket Service", "Java", "Ведение списка выбранных товаров")
        ComponentDb(mongodb_basket, "Basket DB", "MongoDB", "Товары в корзине, кешированные данные")
    }

    Container_Boundary(account, "Account Microservice", "Личный кабинет") {
        Component(accountService, "Account Service", "Java", "Ведение личных данных пользователей, пользовательские действия")
        ComponentDb(postgres_account, "Account DB", "PostgreSQL", "Пользовательские данные")
    }

    Container_Boundary(order, "Order Microservice", "Сервис заказов") {
        Component(orderService, "Order Service", "Java", "Ведение информации о заказах")
        Component(orderReader, "Order Reader", "Java", "Чтение из БД событий")
        ComponentDb(kurrentdb_order, "Order DB", "KurrentDB", "Event sourcing DB")
    
        ' Order CQRS
        Rel(orderService, kurrentdb_order, "Пишет", "gRPC")
        Rel(kurrentdb_order, orderReader, "Читает", "gRPC")
    }
    
    Container_Boundary(delivery, "Delivery Microservice", "Сервис доставки") {
        Component(deliveryService, "Delivery Service", "Java", "Ведение доступных способов доставки, оформление и мониторинг доставки")
        ComponentDb(postgres_delivery, "Delivery DB", "PostgreSQL", "Информация о доступных способах доставки и заявках на доставку")
    }
    
    Container_Boundary(payment, "Payment Microservice", "Сервис оплаты") {
        Component(paymentService, "Payment Service", "Java", "Проведение оплаты")
        ComponentDb(postgres_payment, "Payment DB", "PostgreSQL", "Сохраненные способы оплаты")
    }

    ' Topics
    ComponentQueue(topic_orders, "Топик событий 'Заказ оформлен'", "Apache Kafka")
    ComponentQueue(topic_bookings, "Топик событий 'Товар забронирован'", "Apache Kafka")
    ComponentQueue(topic_payments, "Топик событий 'Платеж подтвержден'", "Apache Kafka")
    
    ' Gateway-Service relations
    Rel(api_gateway, orderReader, "Uses", "GraphQL")
    ' Rel(api_gateway, catalog, "Uses", "GraphQL")
    ' Rel(api_gateway, basket, "Uses", "GraphQL")
    ' Rel(api_gateway, account, "Uses", "GraphQL")
    ' Rel(api_gateway, order, "Uses", "GraphQL")
    ' Rel(api_gateway, delivery, "Uses", "GraphQL")
    ' Rel(api_gateway, payment, "Uses", "GraphQL")

    ' Kafka-sub
    Rel(basketService, topic_bookings, "Потребляет", "Kafka")
    Rel(paymentService, topic_bookings, "Потребляет", "Kafka")
    Rel(storeService, topic_orders, "Потребляет", "Kafka")
    Rel(deliveryService, topic_orders, "Потребляет", "Kafka")
    Rel(deliveryService, topic_payments, "Потребляет", "Kafka")
    Rel(notificationService, topic_orders, "Потребляет", "Kafka")
    Rel(notificationService, topic_payments, "Потребляет", "Kafka")
    Rel(orderService, topic_orders, "Потребляет", "Kafka")
    Rel(orderService, topic_payments, "Потребляет", "Kafka")

    ' Kafka-pub
    Rel(storeService, basketService, "Событие 'Пользователь изменил товар в корзине'", "Kafka")
    Rel(deliveryService, orderService, "Событие 'Статус доставки изменился'", "Kafka")
    Rel(basketService, topic_orders, "Публикует", "Kafka")
    Rel(storeService, topic_bookings, "Публикует", "Kafka")
    Rel(paymentService, topic_payments, "Публикует", "Kafka")
}

Person(user, "User", "Interacts with frontend")
Person(seller, "Seller", "Send orders")

Rel(user, api_gateway, "Uses", "GraphQL")
Rel(notificationService, seller, "Notifies", "Mail/Other")

@enduml